First PR
iffifan/winnie-client pull request #1
Opened 2024-03-11 11:28 UTC by iffifan

2024-03-18 09:25 UTC, kevzz1994 requested changes

2024-03-18 09:25 UTC, kevzz1994 commented on config/winnie-client.php
> +return [
Remove the default values, endpoints should not be publicly visible

2024-03-18 09:25 UTC, kevzz1994 commented on src/Http/Middleware/CheckWinnieUser.php
> +            if ( ! $user->hasRole($role)) {
Fix spacing

2024-03-18 09:25 UTC, kevzz1994 commented on tests/Dummy/User.php
> +    public static function updateOrCreate(array $criteria, array $data): User
This doesn't do anything?

2024-03-19 07:04 UTC, iffifan commented on tests/Dummy/User.php
> +    public static function updateOrCreate(array $criteria, array $data): User
I had to mimic updateOrCreate method of model class of laravel.

2024-03-19 07:07 UTC, iffifan commented on src/Http/Middleware/CheckWinnieUser.php
> +            if ( ! $user->hasRole($role)) {
Updated

2024-03-19 07:07 UTC, iffifan commented on config/winnie-client.php
> +return [
Updated

2024-03-20 14:35 UTC, kevzz1994 approved these changes

2024-03-21 05:25 UTC, merged